markdown: kramdown
highlighter: pygments #rouge
permalink: /:year/:month/:day/:title/
repository: https://github.com/california-civic-data-coalition/california-civic-data-coalition.github.io.git

prose:
  media: "img"

gems:
  - jemoji
